export const ADD_TO_EXPENSE = 'ADD_TO_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const REMOVE_FROM_EXPENSE = 'REMOVE_FROM_EXPENSE';
export const EMPTY_EXPENSE_LIST = 'EMPTY_EXPENSE_LIST';
